[package]
name = "aabb_physics"
version = "0.1.0"
edition = "2024"

description = "A simple 2D physics library based on AABB collision detection."
license = "MIT"
readme = "README.md"
repository = "https://github.com/VojtaKing/aabb_physics"

keywords = ["physics", "2d", "aabb", "collision", "gamedev"]
categories = ["game-development", "simulation"]

[dependencies]
macroquad = "0.4"
